In [1]:
import pandas as pd  # For data analysis
import numpy as np  # For linear algebra and arrays
import json  # For reading and writing JSON data

In [2]:
def load_json_data(file_path):
    """
    Load JSON data from a file.
    
    Parameters:
    file_path (str): The path to the JSON file.
    
    Returns:
    dict: The JSON data loaded as a dictionary, or None if an error occurs.
    """
    try:
        # Attempt to open and read the JSON file at the specified path
        with open(file_path, 'r') as file:
            data = json.load(file)  # Parse the JSON content into a Python dictionary
        print(f"Successfully loaded data from {file_path}")  # Print success message
        return data  # Return the loaded data.
    except FileNotFoundError:
        # Handle the error if the specified file is not found
        print(f"Error: The file '{file_path}' was not found.")
        return None  # Return None to indicate failure
    except json.JSONDecodeError:
        # Handle the error if the file content cannot be decoded as valid JSON.
        print(f"Error: Failed to decode JSON from '{file_path}'. Please check the file format.")
        return None  # Return None to indicate failure

# Example usage:
# Load data from specific JSON files related to an ARC challenge

agi_evaluation_challenges = load_json_data('./arc_data/arc-agi_evaluation_challenges.json')
# Loads the JSON file containing challenges for the AGI evaluation set

agi_evaluation_solutions = load_json_data('./arc_data/arc-agi_evaluation_solutions.json')
# Loads the JSON file containing solutions for the AGI evaluation set

agi_test_challenges = load_json_data('./arc_data/arc-agi_test_challenges.json')
# Loads the JSON file containing challenges for the AGI test set

agi_training_challenges = load_json_data('./arc_data/arc-agi_training_challenges.json')
# Loads the JSON file containing challenges for the AGI training set

agi_training_solutions = load_json_data('./arc_data/arc-agi_training_solutions.json')
# Loads the JSON file containing solutions for the AGI training set

Successfully loaded data from ./arc_data/arc-agi_evaluation_challenges.json
Successfully loaded data from ./arc_data/arc-agi_evaluation_solutions.json
Successfully loaded data from ./arc_data/arc-agi_test_challenges.json
Successfully loaded data from ./arc_data/arc-agi_training_challenges.json
Successfully loaded data from ./arc_data/arc-agi_training_solutions.json


In [3]:
for i in agi_training_challenges:
    task = agi_training_challenges[i]
    train_grid = task['train']
    for t in train_grid:
        for ti in t:
            print(f"{ti} : ")
            print(t[ti])

input : 
[[0, 7, 7], [7, 7, 7], [0, 7, 7]]
output : 
[[0, 0, 0, 0, 7, 7, 0, 7, 7], [0, 0, 0, 7, 7, 7, 7, 7, 7], [0, 0, 0, 0, 7, 7, 0, 7, 7], [0, 7, 7, 0, 7, 7, 0, 7, 7], [7, 7, 7, 7, 7, 7, 7, 7, 7], [0, 7, 7, 0, 7, 7, 0, 7, 7], [0, 0, 0, 0, 7, 7, 0, 7, 7], [0, 0, 0, 7, 7, 7, 7, 7, 7], [0, 0, 0, 0, 7, 7, 0, 7, 7]]
input : 
[[4, 0, 4], [0, 0, 0], [0, 4, 0]]
output : 
[[4, 0, 4, 0, 0, 0, 4, 0, 4], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 4, 0, 0, 0, 0, 0, 4, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 4, 0, 4, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 4, 0, 0, 0, 0]]
input : 
[[0, 0, 0], [0, 0, 2], [2, 0, 2]]
output : 
[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 0, 0, 0, 2, 0, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 0, 0, 0, 2], [2, 0, 2, 0, 0, 0, 2, 0, 2]]
input : 
[[6, 6, 0], [6, 0, 0], [0, 6, 6]]
output : 
[[

In [7]:
# 0-9 then tokens for grid start, grid end and new row
one_hot_max = 10 + 3
start_grid = 10
new_line = 11
end_grid = 12
challenge_keys = list(agi_training_challenges.keys())
encode_test_task = agi_training_challenges[challenge_keys[34]]["train"]

def encode_one_hot_with_start_and_end(grid_in):
    grid_array = np.array(grid_in)
    padded = np.pad(grid_array, pad_width=((0, 0), (0, 1)), mode='constant', constant_values=new_line)
    flattened = padded.flatten()
    padded = np.pad(flattened, (1,1), "constant", constant_values=(start_grid, end_grid))
    one_hot = np.squeeze(np.eye(one_hot_max)[padded.reshape(-1)])
    print(padded)
    print(one_hot.shape)
    return


encode_one_hot_with_start_and_end(encode_test_task[1]['input'])


[10  0  0  0  0  7  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0 11  0
  0  0  0  0  0  0  0  0  0 11  6  0  0  8  8  8  0  0  0  0 11  0  0  0
  8  8  8  0  0  0  0 11  0  0  0  8  8  8  0  0  0  2 11  0  0  0  8  8
  8  0  0  0  0 11  3  0  0  8  8  8  0  0  0  0 11  0  0  0  0  0  0  0
  0  0  0 11  0  0  0  0  0  1  0  0  0  0 11 12]
(112, 13)


In [9]:
def pad_to_30x30(grid, pad_value=-1):
    # Get the current grid size
    rows, cols = grid.shape

    # Calculate the padding needed for rows and columns
    pad_top = (30 - rows) // 2
    pad_bottom = 30 - rows - pad_top
    pad_left = (30 - cols) // 2
    pad_right = 30 - cols - pad_left

    # Pad the grid with the calculated padding
    padded_grid = np.pad(
        grid,
        pad_width=((pad_top, pad_bottom), (pad_left, pad_right)),
        mode='constant',
        constant_values=pad_value
    )

    return padded_grid

# Example usage
grid = np.random.randint(1, 10, (6, 12))  # A 6x12 grid
padded_grid = pad_to_30x30(grid)
print(np.array(encode_test_task[0]["input"]))
padded_in = pad_to_30x30(np.array(encode_test_task[0]["input"]))
padded_out = pad_to_30x30(np.array(encode_test_task[0]["output"]))
print(padded_in.shape)
print(padded_in - padded_out)

[[0 0 0 0 9 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 8 8 0 0 0 0]
 [0 0 0 0 8 8 0 0 0 0]
 [0 0 0 0 8 8 0 0 0 0]
 [6 0 0 0 8 8 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]]
(30, 30)
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0]
